### PR TITLE
Details pages

### PR DESCRIPTION
**Pull request by ryliecc**
Create details pages according to [US13](https://github.com/ryliecc/capstone_webdev_wanikani-app/issues/21)

### CODE REVIEW

**Review by MonaHer — COMMENTED** [review]
Hey Rylie, nice code! I think it's very clear :) I don't have any suggestions for improvement. As I am in my first capstone week (and don't feel so secure about understanding codes I didn't see before), I think I'm just not really able to give helpful hints to your code. But as you will finish your capstone very soon, I would recommend, that maybe you put the PR again in the thread, so maybe someone else, could make some suggestions. I'm so sorry, if this has cost you some time now ! I hope you can understand :)

**Comment by ryliecc** [comment]
> Hey Rylie, nice code! I think it's very clear :) I don't have any suggestions for improvement. As I am in my first capstone week (and don't feel so secure about understanding codes I didn't see before), I think I'm just not really able to give helpful hints to your code. But as you will finish your capstone very soon, I would recommend, that maybe you put the PR again in the thread, so maybe someone else, could make some suggestions. I'm so sorry, if this has cost you some time now ! I hope you can understand :)

No worries. I posted it into code-reviews again. Just fyi, I have only just finished week 2 of the capstone project, so finishing "very soon" is debatable 😅😂

**Comment by MonaHer** [comment]
> 

Ah okay, I was so stressed, because I thought you would be in the course, that finishes this week! 😅 Puh, now I'm a bit relieved haha. 😊 Thanks for your understanding!

**Review by TmWgnr — APPROVED** [review]
LGTM🚀

**Pull request merged**
