### PR TITLE
Display api data

### PR DESCRIPTION
**Pull request by ryliecc**
Display API data according to [US12](https://github.com/ryliecc/capstone_webdev_wanikani-app/issues/20)

### CODE REVIEW

**Comment by CarstenJahnke** [comment]
vercel is not deploying, check the error log :)

**Comment by ryliecc** [comment]
> vercel is not deploying, check the error log :)

I know, I was hoping for some help by a reviewer. I can't find the reason why it won't deploy, because if I use `npm run build` and `npm run dev` everything works perfectly fine. I also put in the error log message to Chat GPT, but it's solutions won't help me either.

**Review by dimitriosxmi — APPROVED** [review]
xD amazing where errors sometimes stem from odd that you still were able to build without issues with a disfunctional import 🤔

**Comment by ryliecc** [comment]
> xD amazing where errors sometimes stem from odd that you still were able to build without issues with a disfunctional import 🤔

I actually changed the file name to useUser.js but for some weird reason it did not push that, but of course I changed the import in the corresponding components. So it worked locally because the import was right there, but it didn't on vercel because it was broken there. Will ask the coaches about that on monday, because not pushing changed file names can ruin everything pretty quickly. Thankfully someone from my student group pointed that out to me, otherwise I would've spent ages looking for the bug.

**Pull request merged**
