### PR TITLE
Add first Vocabulary list

### PR DESCRIPTION
**Pull request by ryliecc**
First setup and first vocabulary list added.
[User Story](https://github.com/ryliecc/capstone_webdev_wanikani-app/issues/1)

### CODE REVIEW

**Comment by dimitriosxmi** [comment]
## LGTM! ⭐ 
Note: Simple straightforward very easy to read (apart from the data.js which I believe won't be necessary to review xD hehe)

**Comment by dimitriosxmi** [comment]
Since it your first PR for capstone prolly a useful reminder to put it in quality assurance before merging 😉

**Comment by dimitriosxmi** [comment]
Oh one more note, idk if you intend to apply styled components later but if you didn't well a heads up to do that eventually 😋

**Review by julialoeschel — COMMENTED** [review]
great, easy to read good code quality. 

one thing! 
we will use Styled components, please avoid any className and implement your stylings with styled components. 
A mix will work, but is very bad practice.

**Comment by ryliecc** [comment]
> Oh one more note, idk if you intend to apply styled components later but if you didn't well a heads up to do that eventually 😋

Styling will be applied later, for now I just need it to work :) I already have a concept for how I want to style everything, but that will probably be a whole PR on itself. I like to do things step by step.

**Comment by ryliecc** [comment]
I just added styled components. :)

**Review by dimitriosxmi — APPROVED** [review]
## LGTM
Notes: Very nice :D now the html is self explanatory

**Pull request merged**
